### ISSUE TITLE
How to load the trained model for predicting new data?

### ISSUE THREAD

**Issue by HazelSCUT** [AutoViML/AutoViML#1]
I used the Catboost to train the model and saved the trained model by using the code (m.save_model('Catboost.dump')).

However, when I failed to load such a saved model for predicting the new data unless I trained the model again.

The question is how to load such a model for predicting new data without training the model each time.

Thanks!

**Comment by AutoViML** [comment]
Sorry I don't understand the question here. Please give code snippets when asking next time.
